spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation

server:
  port: 8084


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/